#include<LPC21XX.h>
#include<string.h>
#include<stdlib.h>
#include"defines.h"
#include"types.h"
#include"delay.h"
#include"i2c_defines.h"
#include"i2c_eeprom.h"
#include"lcddefines.h"
#include"i2c.h"

void pan_card(void)
{
if(password())
{
CmdLCD(CLEAR_LCD);
CmdLCD(GOTO_LINE1_POS0);
strLCD("NAME:");
CmdLCD(GOTO_LINE1_POS0+5);
strLCD("D.SUPRIYA");
CmdLCD(GOTO_LINE2_POS0);
strLCD("DOB:");
u32LCD(15);
charLCD('/');
u32LCD(1);
charLCD('/');
u32LCD(2002);
CmdLCD(GOTO_LINE3_POS0);
strLCD("PAN_CARD_NUM");
strLCD("99AA88BB");
delay_s(5);
}
}
